services:
  postgres:
    image: postgres:latest
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - "/Users/mbsanchez/Documents/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
